### ISSUE TITLE
LoursFree

### ISSUE THREAD

**Issue by muhammedelibrahim** [HWHardsoft/Arduino-MBUS-repeater#5]
I can not find the software on the internet , and the link in the main page is not vaild any more, can you proivde a new link , or can you upload the software if you have it.
https://www.m-bus.de/lorus_download/lor261021.zip

**Comment by HWHardsoft** [comment]
It looks like the developer of LorusFree will not longer provide this program on his website for download. Luckily there is the Internet Archive:

https://web.archive.org/web/20220817155914/https://www.m-bus.de/lorus_download/lor240122.zip
